//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class banners
    {
        public int IdBanner { get; set; }
        public string HomeBannerImage { get; set; }
        public string HomeBannerLink { get; set; }
        public string ListBannerImage { get; set; }
        public string ListBannerLink { get; set; }
        public Nullable<int> IdState { get; set; }
    }
}
