//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.companyStore = new HashSet<companyStore>();
            this.companySubscription = new HashSet<companySubscription>();
            this.product = new HashSet<product>();
            this.userCompany = new HashSet<userCompany>();
        }
    
        public int IdCompany { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<System.DateTime> ModificationDatetime { get; set; }
        public Nullable<System.DateTime> DeletionDatetime { get; set; }
    
        public virtual ICollection<companyStore> companyStore { get; set; }
        public virtual ICollection<companySubscription> companySubscription { get; set; }
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<userCompany> userCompany { get; set; }
    }
}
