//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class devicetypes
    {
        public devicetypes()
        {
            this.profile = new HashSet<profile>();
        }
    
        public int IdDeviceType { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<profile> profile { get; set; }
    }
}
