//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class geoRequest
    {
        public int IdGeoRequest { get; set; }
        public int IdUser { get; set; }
        public int TimesDone { get; set; }
        public System.DateTime RequestDatetime { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
