//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class images
    {
        public int IdImage { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> IdOffer { get; set; }
        public Nullable<int> IdStore { get; set; }
    
        public virtual offer offer { get; set; }
        public virtual product product { get; set; }
        public virtual store store { get; set; }
    }
}
