//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissions
    {
        public int idPermission { get; set; }
        public int IdRole { get; set; }
        public Nullable<short> Read { get; set; }
        public Nullable<short> Create { get; set; }
        public Nullable<short> Update { get; set; }
        public Nullable<short> Delete { get; set; }
    
        public virtual role role { get; set; }
    }
}
