//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.permissions = new HashSet<permissions>();
            this.user = new HashSet<user>();
        }
    
        public int idRole { get; set; }
        public string Name { get; set; }
        public string Rolescol { get; set; }
    
        public virtual ICollection<permissions> permissions { get; set; }
        public virtual ICollection<user> user { get; set; }
    }
}
