//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public state()
        {
            this.profile = new HashSet<profile>();
            this.store = new HashSet<store>();
        }
    
        public string IdState { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<System.DateTime> ModificationDatetime { get; set; }
        public Nullable<System.DateTime> DeletionDatetime { get; set; }
    
        public virtual ICollection<profile> profile { get; set; }
        public virtual ICollection<store> store { get; set; }
    }
}
