//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcategory
    {
        public subcategory()
        {
            this.storeCategory = new HashSet<storeCategory>();
        }
    
        public int IdSubCategory { get; set; }
        public string Name { get; set; }
        public int IdCategory { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<System.DateTime> ModificationDatetime { get; set; }
        public Nullable<System.DateTime> DeletionDatetime { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<storeCategory> storeCategory { get; set; }
    }
}
