//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription
    {
        public subscription()
        {
            this.companySubscription = new HashSet<companySubscription>();
        }
    
        public int IdSubscription { get; set; }
        public string Name { get; set; }
        public decimal Pricing { get; set; }
        public int SortFactor { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<System.DateTime> ModificationDatetime { get; set; }
        public Nullable<System.DateTime> DeletionDatetime { get; set; }
        public int Duration { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<companySubscription> companySubscription { get; set; }
    }
}
