//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class userCompany
    {
        public int IdUserCompany { get; set; }
        public int IdUser { get; set; }
        public int IdCompany { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<int> IdStore { get; set; }
    
        public virtual company company { get; set; }
        public virtual store store { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
