//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.geoRequest = new HashSet<geoRequest>();
            this.userCompany = new HashSet<userCompany>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<geoRequest> geoRequest { get; set; }
        public virtual ICollection<userCompany> userCompany { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
