//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class campaign
    {
        public int CampaignId { get; set; }
        public string Step { get; set; }
        public string Resume { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public string MessageAction { get; set; }
        public string MessageActionLabel { get; set; }
        public System.DateTime OriginalStartDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ContinueNextDay { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Success { get; set; }
        public Nullable<int> Fail { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastOs { get; set; }
        public string LockId { get; set; }
        public Nullable<System.DateTime> LockDate { get; set; }
        public Nullable<System.DateTime> FirstExecution { get; set; }
        public Nullable<int> Discarded { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> TestProfileId { get; set; }
        public string UploadToken { get; set; }
        public Nullable<int> ProfileGroupId { get; set; }
        public Nullable<System.DateTime> DeletionDatetime { get; set; }
    }
}
