//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviceos
    {
        public deviceos()
        {
            this.enabledsections = new HashSet<enabledsections>();
            this.imagesizes = new HashSet<imagesizes>();
            this.profilegroupdeviceos = new HashSet<profilegroupdeviceos>();
            this.profiles = new HashSet<profiles>();
        }
    
        public int IdDeviceOs { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<enabledsections> enabledsections { get; set; }
        public virtual ICollection<imagesizes> imagesizes { get; set; }
        public virtual ICollection<profilegroupdeviceos> profilegroupdeviceos { get; set; }
        public virtual ICollection<profiles> profiles { get; set; }
    }
}
