//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviceos
    {
        public deviceos()
        {
            this.profile = new HashSet<profile>();
        }
    
        public int IdDeviceOs { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<profile> profile { get; set; }
    }
}
