//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class devicetypes
    {
        public devicetypes()
        {
            this.profiles = new HashSet<profiles>();
        }
    
        public int IdDeviceType { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<profiles> profiles { get; set; }
    }
}
