//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class failednotification
    {
        public int CampaignId { get; set; }
        public int ProfileId { get; set; }
        public string Xid { get; set; }
        public string Os { get; set; }
        public string Error { get; set; }
        public string ErrorDetail { get; set; }
        public System.DateTime ProcessedDate { get; set; }
    }
}
