//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lookbookattributecategories
    {
        public lookbookattributecategories()
        {
            this.lookbookattributes = new HashSet<lookbookattributes>();
        }
    
        public int IdLookBookAttributeCategory { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<System.DateTime> ModificationDatetime { get; set; }
        public Nullable<System.DateTime> DeletionDatetime { get; set; }
    
        public virtual ICollection<lookbookattributes> lookbookattributes { get; set; }
    }
}
