//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lookbookitemattributes
    {
        public int idLookBookItemAttribute { get; set; }
        public int IdLookBookItem { get; set; }
        public int IdLookBookAttribute { get; set; }
    
        public virtual lookbookattributes lookbookattributes { get; set; }
        public virtual lookbookitems lookbookitems { get; set; }
    }
}
