//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lookbookattributes
    {
        public lookbookattributes()
        {
            this.lookbookitemattributes = new HashSet<lookbookitemattributes>();
        }
    
        public int IdLookBookAttribute { get; set; }
        public int IdLookBookAttributeCategory { get; set; }
        public string Name { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<System.DateTime> ModificationDatetime { get; set; }
        public Nullable<System.DateTime> DeletionDatetime { get; set; }
    
        public virtual lookbookattributecategories lookbookattributecategories { get; set; }
        public virtual ICollection<lookbookitemattributes> lookbookitemattributes { get; set; }
    }
}
