//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuponeraEntities : DbContext
    {
        public CuponeraEntities()
            : base("name=CuponeraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<coupons> coupons { get; set; }
        public DbSet<deviceos> deviceos { get; set; }
        public DbSet<devicetypes> devicetypes { get; set; }
        public DbSet<enabledsections> enabledsections { get; set; }
        public DbSet<homeoffers> homeoffers { get; set; }
        public DbSet<imagesizes> imagesizes { get; set; }
        public DbSet<lookbookattributecategories> lookbookattributecategories { get; set; }
        public DbSet<lookbookattributes> lookbookattributes { get; set; }
        public DbSet<lookbookitemattributes> lookbookitemattributes { get; set; }
        public DbSet<lookbookitems> lookbookitems { get; set; }
        public DbSet<modules> modules { get; set; }
        public DbSet<permissions> permissions { get; set; }
        public DbSet<prehomeimages> prehomeimages { get; set; }
        public DbSet<profilegroups> profilegroups { get; set; }
        public DbSet<profiles> profiles { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<socialfeedaccesslog> socialfeedaccesslog { get; set; }
        public DbSet<socialupdates> socialupdates { get; set; }
        public DbSet<states> states { get; set; }
        public DbSet<stores> stores { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<users> users { get; set; }
    }
}
