//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class profilegroupdeviceos
    {
        public int IdProfileGroupDeviceOs { get; set; }
        public int IdProfileGroup { get; set; }
        public int IdDeviceOs { get; set; }
    
        public virtual deviceos deviceos { get; set; }
        public virtual profilegroups profilegroups { get; set; }
    }
}
