//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class profilegroups
    {
        public profilegroups()
        {
            this.coupons = new HashSet<coupons>();
        }
    
        public int IdProfileGroup { get; set; }
        public string Name { get; set; }
        public Nullable<int> IsFixed { get; set; }
        public string AppVersion { get; set; }
        public Nullable<int> Geolocation { get; set; }
        public Nullable<int> PushNotification { get; set; }
        public Nullable<int> SMSNotification { get; set; }
        public Nullable<int> EmailNotification { get; set; }
        public Nullable<int> PostalNotification { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MembersCount { get; set; }
        public Nullable<System.DateTime> MembersComputingDatetime { get; set; }
        public string LockId { get; set; }
        public Nullable<System.DateTime> LockDate { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<System.DateTime> ModificationDatetime { get; set; }
        public Nullable<System.DateTime> DeletionDatetime { get; set; }
    
        public virtual ICollection<coupons> coupons { get; set; }
    }
}
