//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.permissions = new HashSet<permissions>();
            this.user = new HashSet<user>();
        }
    
        public int idRole { get; set; }
        public string Name { get; set; }
        public string Rolescol { get; set; }
    
        public virtual ICollection<permissions> permissions { get; set; }
        public virtual ICollection<user> user { get; set; }
    }
}
