//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class socialupdates
    {
        public int IdSocialUpdate { get; set; }
        public string IdSourceItem { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public string ImageURL { get; set; }
        public string TargetURL { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> SocialItemDatetime { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<System.DateTime> ModificationDatetime { get; set; }
        public Nullable<System.DateTime> DeletionDatetime { get; set; }
    }
}
