//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class socialfeedaccesslog
    {
        public int IdSocialFeedAccessLog { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> ModificationDatetime { get; set; }
    }
}
