//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlscriptlog
    {
        public string Id { get; set; }
        public string FileName { get; set; }
        public string Iteration { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime ExecutionDateTime { get; set; }
        public int ExecutionStatus { get; set; }
        public short Forced { get; set; }
        public string HashCode { get; set; }
        public byte[] Timestamp { get; set; }
    }
}
