//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class states
    {
        public states()
        {
            this.profiles = new HashSet<profiles>();
            this.stores = new HashSet<stores>();
        }
    
        public string IdState { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<profiles> profiles { get; set; }
        public virtual ICollection<stores> stores { get; set; }
    }
}
