//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuponera.Backend.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription
    {
        public subscription()
        {
            this.companySubscription = new HashSet<companySubscription>();
        }
    
        public string Name { get; set; }
        public decimal Pricing { get; set; }
        public int SortFactor { get; set; }
        public int Idsubscription { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<System.DateTime> ModificationDatetime { get; set; }
        public Nullable<System.DateTime> DeletionDatetime { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ICollection<companySubscription> companySubscription { get; set; }
    }
}
